# echo 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPMmo3NvDNNeXV1OzCTPINkrywWjgXKpmZvnHys2w25u root@gha-runner' >> ~/.ssh/authorized_keys

name: code-server

secrets:
  code-server-password:
    environment: CODE_SERVER_PASSWORD
  ssh-vps-private-key:
    environment: SSH_VPS_PRIVATE_KEY
  ssh-vps-public-key:
    environment: SSH_VPS_PUBLIC_KEY
  namecheap-username:
    environment: NAMECHEAP_USERNAME
  namecheap-api-key:
    environment: NAMECHEAP_API_KEY

volumes:
  swag_etc:
  swag_keys:

services:
  code-server:
    container_name: code-server
    restart: always
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker:/var/lib/docker
      - /root/workspace:/root/workspace
    secrets:
      - code-server-password
      - ssh-vps-private-key
      - ssh-vps-public-key
    healthcheck:
      test: curl -f http://localhost:81 || exit 1
      interval: 5s
    build:
      pull: true
      dockerfile_inline: |
        FROM debian:latest
        RUN apt update && apt install -y --no-install-recommends \
                ca-certificates \
                curl \
                htop \
                jq \
                tree \
                unzip \
                wget \
                zip \
              && rm -rf /var/lib/apt/lists/*
        RUN curl -fsSL https://get.docker.com | sh
        RUN curl -fsSL https://deb.nodesource.com/setup_24.x | bash && \
              apt install -y --no-install-recommends nodejs && rm -rf /var/lib/apt/lists/*
        RUN curl -fsSL https://code-server.dev/install.sh | sh && \
              code-server --install-extension angular.ng-template \
                          --install-extension dbaeumer.vscode-eslint \
                          --install-extension esbenp.prettier-vscode
        RUN cat << EOF > ~/.local/share/code-server/User/settings.json
        {
          "workbench.colorTheme": "Dark+",
          "git.enableSmartCommit": true,
          "git.confirmSync": false,
          "git.autofetch": true,
          "[typescript]": {
            "editor.defaultFormatter": "esbenp.prettier-vscode"
          },
          "[javascript]": {
            "editor.defaultFormatter": "esbenp.prettier-vscode"
          },
          "editor.formatOnSave": true
        }
        EOF
        RUN git config --global user.email "d.landgraf2000@icloud.com" && \
            git config --global user.name "daniel2202x" && \
            git config --global pull.rebase false
        RUN cat << 'EOF_ENTRYPOINT' > /entrypoint.sh
        #!/bin/sh
        set -e
        cat << EOF_CODE_SERVER_CONF > ~/.config/code-server/config.yaml
        bind-addr: 0.0.0.0:81
        auth: password
        password: "$(cat /run/secrets/code-server-password)"
        cert: false
        EOF_CODE_SERVER_CONF
        cp /run/secrets/ssh-vps-private-key ~/.ssh/id_ed25519
        cp /run/secrets/ssh-vps-public-key ~/.ssh/id_ed25519.pub
        chmod 600 ~/.ssh/id_ed25519 ~/.ssh/id_ed25519.pub
        echo >> ~/.ssh/id_ed25519
        exec code-server
        EOF_ENTRYPOINT
        RUN chmod +x /entrypoint.sh
        ENTRYPOINT ["/entrypoint.sh"]

  swag:
    container_name: swag
    restart: always
    ports:
      - 80:80
      - 443:443
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PUID: 1000
      PGID: 1000
      TZ: UTC
      URL: dev.fluently.to
      VALIDATION: dns
      DNSPLUGIN: namecheap
    volumes:
      - swag_etc:/config/etc
      - swag_keys:/config/keys
    secrets:
      - namecheap-username
      - namecheap-api-key
    healthcheck:
      test: curl -f http://localhost:80 || exit 1
      start_period: 3m
      interval: 5s
    build:
      pull: true
      dockerfile_inline: |
        FROM linuxserver/swag:latest
        RUN cat << 'EOF' > /defaults/nginx/site-confs/default.conf.sample
        server {
            listen 80 default_server;
            listen [::]:80 default_server;
            location / {
                return 301 https://$$host$$request_uri;
            }
        }
        server {
            listen 443 ssl default_server;
            listen [::]:443 ssl default_server;
            server_name _;
            include /config/nginx/ssl.conf;
            location / {
              proxy_pass http://host.docker.internal:81/;
              proxy_set_header Host $$http_host;
              proxy_set_header Upgrade $$http_upgrade;
              proxy_set_header Connection upgrade;
              proxy_set_header Accept-Encoding gzip;
            }
        }
        EOF
        RUN cat << 'EOF_ENTRYPOINT' > /entrypoint.sh
        #!/bin/sh
        set -e
        cat << EOF_SWAG_NC_INI > /defaults/dns-conf/namecheap.ini
        dns_namecheap_username=$(cat /run/secrets/namecheap-username)
        dns_namecheap_api_key=$(cat /run/secrets/namecheap-api-key)
        EOF_SWAG_NC_INI
        exec /init
        EOF_ENTRYPOINT
        RUN chmod +x /entrypoint.sh
        ENTRYPOINT ["/entrypoint.sh"]
