secrets:
  code-server-password:
    environment: CODE_SERVER_PASSWORD

services:
  code-server:
    container_name: code-server
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: host
    build:
      pull: true
      secrets:
        - code-server-password
      dockerfile_inline: |
        FROM debian:latest
        RUN apt update && apt install -y --no-install-recommends \
                ca-certificates \
                curl \
                htop \
                jq \
                tree \
                unzip \
                wget \
                zip \
              && rm -rf /var/lib/apt/lists/*
        RUN curl -fsSL https://get.docker.com | sh
        RUN curl -fsSL https://deb.nodesource.com/setup_24.x | bash && \
              apt install -y --no-install-recommends nodejs && rm -rf /var/lib/apt/lists/*
        RUN git config --global user.email "d.landgraf2000@icloud.com" && \
            git config --global user.name "daniel2202x" && \
            git config --global pull.rebase false
        RUN curl -fsSL https://code-server.dev/install.sh | sh && \
              code-server --install-extension angular.ng-template \
                          --install-extension dbaeumer.vscode-eslint \
                          --install-extension esbenp.prettier-vscode
        RUN cat << EOF > /root/.local/share/code-server/User/settings.json
        {
          "workbench.colorTheme": "Default Dark+",
          "git.enableSmartCommit": true,
          "git.confirmSync": false,
          "git.autofetch": true,
          "[typescript]": {
            "editor.defaultFormatter": "esbenp.prettier-vscode"
          }
        }
        EOF
        RUN --mount=type=secret,id=code-server-password,required=true \
        cat << EOF > /root/.config/code-server/config.yaml
        bind-addr: 0.0.0.0:8080
        auth: password
        password: $(cat /run/secrets/code-server-password)
        cert: false
        EOF
        ENTRYPOINT ["code-server"]
