services:
  letsencrypt:
    image: linuxserver/swag:4.2.0
    container_name: letsencrypt
    environment:
      PUID: 1000
      PGID: 1000
      TZ: UTC
      URL: dev.fluently.to
      SUBDOMAINS: ""
      VALIDATION: http
      EMAIL: d.landgraf2000@icloud.com
    ports:
      - 80:80
      - 443:443
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./default.conf:/config/nginx/site-confs/default.conf
      - ./letsencrypt_data:/config/etc/letsencrypt
