name: Deploy code-server on VPS

on:
  push:
    branches:
      - main

concurrency:
  group: deploy-workflow
  cancel-in-progress: false

jobs:
  deploy-code-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H dev.fluently.to >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Verify or install Docker
        run: ssh root@dev.fluently.to 'docker --version || (curl -fsSL https://get.docker.com | sh)'

      - name: Install code-server
        run: |
          export SSH_VPS_PRIVATE_KEY_BASE64=$(echo "$SSH_VPS_PRIVATE_KEY" | base64 -w 0)
          cat docker-compose.vps.yml | ssh root@dev.fluently.to "
            export CODE_SERVER_PASSWORD=$CODE_SERVER_PASSWORD
            export SSH_VPS_PRIVATE_KEY=\$(echo "$SSH_VPS_PRIVATE_KEY_BASE64" | base64 -d)
            export SSH_VPS_PUBLIC_KEY='$SSH_VPS_PUBLIC_KEY'
            export NAMECHEAP_USERNAME=$NAMECHEAP_USERNAME
            export NAMECHEAP_API_KEY=$NAMECHEAP_API_KEY
            docker compose -f - up --build --force-recreate --renew-anon-volumes --wait
          "
        env:
          CODE_SERVER_PASSWORD: ${{ secrets.CODE_SERVER_PASSWORD }}
          SSH_VPS_PRIVATE_KEY: ${{ secrets.SSH_VPS_PRIVATE_KEY }}
          SSH_VPS_PUBLIC_KEY: ${{ secrets.SSH_VPS_PUBLIC_KEY }}
          NAMECHEAP_USERNAME: ${{ secrets.NAMECHEAP_USERNAME }}
          NAMECHEAP_API_KEY: ${{ secrets.NAMECHEAP_API_KEY }}
